### ISSUE TITLE
Windows standalone version missing electron compiler error

### ISSUE THREAD

**Issue by hutianyi003** [httptoolkit/feedback#16]
The standalone version cannot be loaded because there is no electron compiler, as this message indicates.

![image](https://user-images.githubusercontent.com/5686999/51016829-b662d780-15ac-11e9-81b1-66b680c3a51a.png)

My system is Windows 10 1809 up to date (17763.253).
I've tried put it another place to avoid space in the path, but the error still exists.
Do I need install something beforehand?

**Comment by pimterry** [comment]
Hmm, that's very unusual! Nothing should be required, and I've tested windows installs on a couple of machines myself with no trouble, so I'm not sure.

Thanks for the report though, I'm sure there's other people hitting this issue, and it's really hard for me to catch every case like this on desktop installs myself.

Can you zip up the install directory, and send it to me (with a Google drive link or similar, since it'll be massive), so I can take a closer look?

Once you've done that, can you try uninstalling and reinstalling, just to know if that helps?

Is there anything else unusual about your system that you can think of?

I'll investigate further myself, but the above would really help, thanks!

**Comment by hutianyi003** [comment]
Hi Tim, the error message comes from the standalone version, which is the windows standalone zip directly downloaded from https://httptoolkit.tech/view/, and I don't change any file.
Today I tried the installer version but it cannot work either. This time nothing happens. When I click the program no windows or message pop up. 
I use my computer for some develop task but I don't do anything about electron before.

**Comment by pimterry** [comment]
Quick update @hutianyi003, I'm pretty sure this is caused by this issue: https://github.com/electron-userland/electron-forge/issues/670.

I've been mainly testing the installer versions up until now, and it's exclusively the Windows standalone build that's broken, sorry that slipped through the net. I'm going to try to get this fixed, but it's non-trivial, so for now I've disabled the Windows standalone download option entirely.

The installer version definitely should work regardless though, and I have been testing that release throughout. Can you tell me any more about how fails for you? 

* Is it that running the installer does nothing, or running the application?
* Can you run it (whichever part is failing) in a CLI, and tell me if there's any output?
* Next time you run it, can you tell me the exact time? There's automatic error reporting included in a few places, and that might let me track down some more detailed information.

Thanks again for the report! I wouldn't have noticed this for ages without your help :+1:

**Comment by pimterry** [comment]
Hmm, this is a tricky one. My error reporting doesn't have any crashes logged on the 19th, so I don't have any more information.

I have done a bunch of bug fixes since the first release though, and made quite a few improvements to the error reporting too to make that more reliable. Can you uninstall the app, download the latest release from [httptoolkit.tech](https://httptoolkit.tech), and let me know what happens? Hopefully that'll either work nicely, or at least give me a bunch more info on what to look into!

**Comment by pimterry** [comment]
@hutianyi003 any thoughts on the above? If it's possible for you to uninstall and test with the latest version to confirm this issue is fixed, I'd really appreciate it.

**Comment by hutianyi003** [comment]
I reinstall the latest version but it still cannot work...
With a message as the picture shows
![image](https://user-images.githubusercontent.com/5686999/52559000-0690bc00-2e2f-11e9-8345-018de1ae995d.png)

**Comment by pimterry** [comment]
Aha, I think I might've found the issue. What's your username on this machine? Does it have a space in it? More specifically does `C:/Users/<username>/` have a space in it?

I've just seen some messages from my error logs that suggest I'm failing to quote a path somewhere, and that could cause this issue. Should be a nice quick fix if that is the problem, I'll start fixing it now anyway.

**Comment by hutianyi003** [comment]
Exactly! There is a space in my username and therefore in the path which is "C:/Users/Hu Tianyi/".

**Comment by pimterry** [comment]
Excellent :smiley:. I've just done some testing of this and fixed a bunch of bugs for this case, and it now seems to work nicely for me testing on Windows. There's a new Windows release available at https://github.com/httptoolkit/httptoolkit-desktop/releases/download/v0.1.4/HTTP.Toolkit-0.1.4.Setup.exe.

Can you download that and check it works for you?

**Comment by hutianyi003** [comment]
It works!
Thanks very much and it looks pretty good!

**Comment by pimterry** [comment]
Amazing! Glad we got that chased down :smiley:. Thanks again for your help, that would've been a tricky one to catch myself, and do let me know if you hit any other issues.
